---
# see: https://github.com/geerlingguy/ansible-role-docker/blob/8bb277bd7fb7019eb129b4a07194f0364c060203/.github/workflows/release.yml
name: Release Role to Ansible Galaxy
on:
  push:
  workflow_dispatch:
  workflow_call:

defaults:
  run:
    working-directory: "${{ GITHUB.REPOSITORY }}"

jobs:
  release:
    name:  Release role to Ansible Galaxy
    runs-on: ubuntu-latest
    # prevent stuck jobs
    timeout-minutes: 20
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: ${{ GITHUB.REPOSITORY }}/.github/actions/set-up-python/

      - name: Set up Ansible
        uses: ${{ GITHUB.REPOSITORY }}/.github/actions/set-up-ansible/

      - name: Publish role with import to Galaxy
        run: >-
          ansible-galaxy role import --api-key ${{ secrets.GALAXY_API_KEY }}
          $(echo ${{ github.repository }} | cut -d/ -f1) $(echo ${{ github.repository }} | cut -d/ -f2)
